name: test

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  firstjob:
           name: First Job
           runs-on: ubuntu-latest
           steps:
           - name: Step1
             uses: actions/checkout@v3
           - name: Step2
             run: |
              touch newfile.yaml
              echo "Put this in that file" >> newfile.yaml
              cat newfile.yaml
              pwd
  secondjob:
            needs: [firstjob]
            name: Second Job
            runs-on: macos-latest
            steps: 
            - name: Step1
              run: date

  thirdjob:
           name: Third Job
           runs-on: windows-latest
           steps:
           - name: Step1
             run: date
  

            
  
              
             
           
